FROM python:3.9

# Install supervisor
RUN apt-get update && apt-get install -y supervisor

RUN mkdir app

RUN cd app

WORKDIR /app

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY . .

ARG DATABASE_URI
ENV DATABASE_URI=${DATABASE_URI}

ARG OPENAI_API_KEY
ENV OPENAI_API_KEY=${OPENAI_API_KEY}

ARG CELERY_BROKER_URL
ENV CELERY_BROKER_URL=${CELERY_BROKER_URL}

ARG result_backend
ENV result_backend=${result_backend}

ARG ELEVENLABS_API_KEY
ENV ELEVENLABS_API_KEY=${ELEVENLABS_API_KEY}

ARG SPACE_REGION
ENV SPACE_REGION=${SPACE_REGION}

ARG SPACE_NAME
ENV SPACE_NAME=${SPACE_NAME}

ARG SPACE_KEY
ENV SPACE_KEY=${SPACE_KEY}

ARG SPACE_SECRET
ENV SPACE_SECRET=${SPACE_SECRET}

ARG SPACE_ENDPOINT
ENV SPACE_ENDPOINT=${SPACE_ENDPOINT}

ARG SPACE_EDGE_ENDPOINT
ENV SPACE_EDGE_ENDPOINT=${SPACE_EDGE_ENDPOINT}

ARG FLASK_DEBUG
ENV FLASK_DEBUG=${FLASK_DEBUG}

ARG SECRET
ENV SECRET=${SECRET}

ARG CELERY_WORKER_MEMORY_LIMIT
ENV CELERY_WORKER_MEMORY_LIMIT=${CELERY_WORKER_MEMORY_LIMIT}

ARG GOOGLE_API_KEY
ENV GOOGLE_API_KEY=${GOOGLE_API_KEY}

ARG DEFAULT_INDEX
ENV DEFAULT_INDEX=${DEFAULT_INDEX}

ARG CONVEX_URL
ENV CONVEX_URL=${CONVEX_URL}

RUN curl -fsSL https://deb.nodesource.com/setup_lts.x | bash -
RUN apt-get install -y nodejs

RUN flask db upgrade

RUN python manage.py


EXPOSE 80

CMD bash -c "supervisord -c supervisord.conf"