"""empty message

Revision ID: fc4ebeb33327
Revises: 96f397919f52
Create Date: 2023-11-04 21:54:36.158996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc4ebeb33327'
down_revision = '96f397919f52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partner', schema=None) as batch_op:
        batch_op.add_column(sa.Column('corpus_id', sa.String(), nullable=True))
        batch_op.create_unique_constraint(None, ['corpus_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partner', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('corpus_id')

    # ### end Alembic commands ###
